name: Build and Test Python distrubutions

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install APT dependencies
      run: |
        sudo apt-get install zipcmp

    - name: Install Python dependencies
      run: |
        python3 -m pip install -r requirements/build_requirements.txt

    - name: Build a Python source distrubution and wheel
      run: |
        ./scripts/build.sh

    - name: Test the wheel
      run: |
        ./scripts/test_wheel.sh

    - name: Test the source distribution
      run: |
        ./scripts/test_source_distribution.sh
