name: Stage distrubutions to test PyPI

on: [workflow_dispatch]

jobs:
  stage:
    environment:
      name: Test PyPI
      url: https://test.pypi.org/project/seligimus/
    env:
      TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Build a Python source distrubution and wheel
      run: |
        ./scripts/build.sh

    - name: Stage the distributions
      run: |
        ./scripts/stage.sh
